### ISSUE TITLE
TCP OSC Server, Client disconnect - non recoverable error

### ISSUE THREAD

**Issue by neophob** [Sciss/NetUtil#1]
Thanks for your OSC Library! I found an error: I created a TCP OSC Server and a TCP Client, communication works. If however the client just disconnects, the console gets flooded with this error:

<pre>
OSCReceiver.run : java.io.IOException : Eine vorhandene Verbindung wurde vom Remotehost geschlossen
</pre>

This error is NOT recoverable, as there is no error handling inside the run method. the stack trace looks like this:

<pre>
Stacktrace:
Caused by: java.io.IOException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(Unknown Source)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.write(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.write(Unknown Source)
        at de.sciss.net.OSCTransmitter$TCPOSCTransmitter.send(OSCTransmitter.java:845)
        at de.sciss.net.OSCTransmitter$TCPOSCTransmitter.send(OSCTransmitter.java:814)
        at de.sciss.net.OSCTransmitter.send(OSCTransmitter.java:498)
        at de.sciss.net.OSCTransmitter.send(OSCTransmitter.java:534)
        at de.sciss.net.OSCClient.send(OSCClient.java:472)
</pre>

the expected behaviour (for me) is, that the `de.sciss.net.OSCClient.send(OSCClient.java:472)` throws an IOException, but this error is just silent. any ideas?

Cheers
Michu

**Comment by Sciss** [comment]
Note that I will close this issue unless there is an update on how to reproduce.
